import numpy as np 
import pandas as pd 

df=pd.read_csv("Iris.csv")
print("====================Head================")
print(df.head(5))
print("====================Shape================")
print(df.shape)
print("====================Describe================")
print(df.describe())
print("====================Is na================")
print(df.isna().sum())
numeric_df = df.drop('Species', axis=1)
print("====================Mean================")
print(numeric_df.mean())
print("====================Median================")
print(numeric_df.median())
print("====================Mode================")
print(numeric_df.mode())
print("====================Standard deviation================")
print(numeric_df.std())
print("===================Sample===================")
print(numeric_df.sample(10))
print("===================Group by mean==============")
print(df['SepalLengthCm'].groupby(df['Species']).mean())
print("===================Group by median==============")
print(df['SepalLengthCm'].groupby(df['Species']).median())
print("===================Group by describe==============")
print(df['SepalLengthCm'].groupby(df['Species']).describe())
